= ISO 10303 STEPmod CVS import to Git

image:https://github.com/metanorma/iso-10303-stepmod-migration/actions/workflows/import.yml/badge.svg["import", link="https://github.com/metanorma/iso-10303-stepmod-migration/actions/workflows/import.yml"]

== Purpose

This repository contains a workflow that imports the ISO 10303
STEPmod CVS repository at Boost to the
https://github.com/metanorma/iso-10303-stepmod-cvs[iso-10303-stepmod-cvs]
Git repository.


== Details

There are two repos involved here:

* Repo with import workflow: https://github.com/metanorma/iso-10303-stepmod-migration
* Repo to hold converted git repo: https://github.com/metanorma/iso-10303-stepmod-cvs

Under `.github/` you will see the `import.yml` workflow.

The workflow depends on these two tools:

. https://gitlab.com/esr/reposurgeon[`reposurgeon`];
. https://gitlab.com/esr/cvs-fast-export[`cvs-fast-export`]

The workflow goes:

. Use `rsync` to retrieve the CVS repository hosted at Boost via `ssh`;

. Run `reposurgeon` with the provided configuration to convert the whole
  repository history into Git;

. Push all Git tags and branches to the
  https://github.com/metanorma/iso-10303-stepmod-cvs["converted" GitHub repo],
  using the `metanorma-ci` GitHub user.

NOTE: The Boost Conseil CVS is located at `cvs.boost-lab.net`.

NOTE: Previous (and deprecated) attempts to do the same are documented at
link:previous-attempts.adoc[].


== Frequency

This workflow is run once a day to import latest changes from Boost CVS.


== Usage

=== Import strategy

Cloning a remote CVS repository while importing is super slow,
especially for a large repository like STEPmod.

We have tested and settled on these steps:

. Maintain a local `rsync` copy of the CVS repository.

. Resolve all names from the CVS repository (CVS only stores UNIX usernames, in
Git are names and emails) with a `reposurgeon` user map.

. Run `reposurgeon` which depends on `cvs-fast-import` to import the CVS
repository into the `iso-10303-stepmod-cvs` Git repo.


=== Creating the `rsync` clone of the CVS repository

[source,sh]
----
rsync -avrPz -e ssh {{username}}@{{cvshost}}:/stepmod/ stepmod-rsync/
----

=== Install reposurgeon

The best repository conversion tool, ever. `reposurgeon` works on Linux and
macOS.

On Ubuntu the version is outdated and does not contain the functionality we need
here, so we must build it from scratch from Git.

Ubuntu:
[source,sh]
----
git clone https://gitlab.com/esr/reposurgeon
cd reposurgeon
git checkout 2f5f83ec63da34beaf8293434b5e1627366dfa7c
sed -i 's/apt-get install /apt-get install -y /' Makefile
make fullinstall
make all
----

The Homebrew macOS version is recent enough to work with our workflow.

macOS:
[source,sh]
----
brew install reposurgeon
----

=== Install cvs-fast-export

`reposurgeon` depends on the `cvs-fast-export` tool which works on Linux and
macOS.

Ubuntu:
[source,sh]
----
$ apt-get -y install cvs-fast-export
----

macOS:
[source,sh]
----
$ brew install cvs-fast-export
----


=== (one time) Setting up the reposurgeon conversion flow

This is a first-time only step that is only needed only when you first setup
`reposurgeon` migration for a repository.

[source,sh]
----
$ cd stepmod
$ repotool initialize stepmod
repotool: what VCS do you want to convert from? cvs
repotool: what VCS do you want to convert to? git
repotool: generating Makefile, some variables in it need to be set.
repotool: generating a stub options file.
repotool: generating a stub lift file.
repotool: generating a stub map file.
----

Then you need to fill in:

* `Makefile` at `READ_OPTIONS =` to determine what to convert into Git branches
* `stepmod.lift` if you want to add additional `reposurgeon` commands

The way to determine what commands to provide reposurgeon is via testing in the `reposurgeon` CLI:

[source,sh]
----
$ reposurgeon
reposurgeon%
----

Please refer to the
http://www.catb.org/~esr/reposurgeon/repository-editing.html[`reposurgeon` manual]
for details.


=== Getting all users for email mapping

Find all authors in the CVS repository using `make stubmap`.

[source,sh]
----
$ cd stepmod
$ make stubmap
----

Then manually edit the `stepmod.map` file to provide author information.


=== Run reposurgeon to convert

After all authors are mapped, run `reposurgeon` to create `stepmod-git`.

[source,sh]
----
$ # assume that stepmod-rsync is the rsync copy
$ cd stepmod
$ # link the rsync'ed copy's /stepmod directory to stepmod-mirror
$ ln -s ../stepmod-rsync/stepmod stepmod-mirror
$ # run reposurgeon to perform conversion
$ make
----

The converted Git repo will be available at `stepmod/stepmod-git`.


=== Upload the converted Git repo

We actually use more complicated steps to upload commits via GHA iteratively
in batches of commits (see import.yaml), but locally the following works.

[source,sh]
----
$ cd stepmod/stepmod-git
$ git remote add origin git@github.com/metanorma/iso-10303-stepmod-cvs
$ git push --all
$ git push --tags
----
